//
//  ListGistsWorker.swift
//  Gists
//
//  Created by Marc Humet on 4/2/16.
//  Copyright (c) 2016 SPM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class ListGistsWorker
{
  // MARK: Business Logic
  
  func doSomeWork()
  {
    // NOTE: Do the work
  }
}
