//
//  ListGistsViewController.swift
//  Gists
//
//  Created by Marc Humet on 4/2/16.
//  Copyright (c) 2016 SPM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ListGistsViewControllerInput
{
  func displaySomething(viewModel: ListGistsViewModel)
}

protocol ListGistsViewControllerOutput
{
  func doSomething(request: ListGistsRequest)
}

class ListGistsViewController: UITableViewController, ListGistsViewControllerInput
{
  var output: ListGistsViewControllerOutput!
  var router: ListGistsRouter!
  
  // MARK: Object lifecycle
  
  override func awakeFromNib()
  {
    super.awakeFromNib()
    ListGistsConfigurator.sharedInstance.configure(self)
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomethingOnLoad()
  }
  
  // MARK: Event handling
  
  func doSomethingOnLoad()
  {
    // NOTE: Ask the Interactor to do some work
    
    let request = ListGistsRequest()
    output.doSomething(request)
  }
  
  // MARK: Display logic
  
  func displaySomething(viewModel: ListGistsViewModel)
  {
    // NOTE: Display the result from the Presenter
    
    // nameTextField.text = viewModel.name
  }
}
