//
//  ListGistsConfigurator.swift
//  Gists
//
//  Created by Marc Humet on 4/2/16.
//  Copyright (c) 2016 SPM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension ListGistsViewController: ListGistsPresenterOutput
{
  override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)
  {
    router.passDataToNextScene(segue)
  }
}

extension ListGistsInteractor: ListGistsViewControllerOutput
{
}

extension ListGistsPresenter: ListGistsInteractorOutput
{
}

class ListGistsConfigurator
{
  // MARK: Object lifecycle
  
  class var sharedInstance: ListGistsConfigurator
  {
    struct Static {
      static var instance: ListGistsConfigurator?
      static var token: dispatch_once_t = 0
    }
    
    dispatch_once(&Static.token) {
      Static.instance = ListGistsConfigurator()
    }
    
    return Static.instance!
  }
  
  // MARK: Configuration
  
  func configure(viewController: ListGistsViewController)
  {
    let router = ListGistsRouter()
    router.viewController = viewController
    
    let presenter = ListGistsPresenter()
    presenter.output = viewController
    
    let interactor = ListGistsInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
