//
//  ListGistsPresenter.swift
//  Gists
//
//  Created by Marc Humet on 4/2/16.
//  Copyright (c) 2016 SPM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ListGistsPresenterInput
{
  func presentSomething(response: ListGistsResponse)
}

protocol ListGistsPresenterOutput: class
{
  func displaySomething(viewModel: ListGistsViewModel)
}

class ListGistsPresenter: ListGistsPresenterInput
{
  weak var output: ListGistsPresenterOutput!
  
  // MARK: Presentation logic
  
  func presentSomething(response: ListGistsResponse)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = ListGistsViewModel()
    output.displaySomething(viewModel)
  }
}
