//
//  ListGistsInteractor.swift
//  Gists
//
//  Created by Marc Humet on 4/2/16.
//  Copyright (c) 2016 SPM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ListGistsInteractorInput
{
  func doSomething(request: ListGistsRequest)
}

protocol ListGistsInteractorOutput
{
  func presentSomething(response: ListGistsResponse)
}

class ListGistsInteractor: ListGistsInteractorInput
{
  var output: ListGistsInteractorOutput!
  var worker: ListGistsWorker!
  
  // MARK: Business logic
  
  func doSomething(request: ListGistsRequest)
  {
    // NOTE: Create some Worker to do the work
    
    worker = ListGistsWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = ListGistsResponse()
    output.presentSomething(response)
  }
    
    func listGists(){
        
    }
}
